### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by alexphelps** [viadeo/snowplow-dashboard#1]
Hi there, your snowplow dashboard project looks really great. I ran into some issues setting it up. 

Do you have a basic installation / setup guide or system requirements?

**Comment by epantera** [comment]
Hi alex,

for sure we need to invest on documentation in next weeks.
Do you already have a [snowplow](http://snowplowanalytics.com) infrastructure running somewhere ?

**Comment by alexphelps** [comment]
Yep, we have snowplow up and running. Now we're just working on how to visualize the data. 

Some basic setup / configuration instructions would be really great!

**Comment by epantera** [comment]
@alexphelps the project was pretty outdated, i made a couple of commits to fix that. We really need to invest few hours in packaging and docs.

Could you please have a look to this doc and tell me if everything is ok for you ?
- [Setup guide for local development](https://github.com/viadeo/snowplow-dashboard/wiki/Installation-guide-for-local-development)
- [Develop your first analytic dashboard in less than 5 min](https://github.com/viadeo/snowplow-dashboard/wiki/Develop-your-first-analytic-dashboard-in-less-than-5-min)

**Comment by alexphelps** [comment]
These are great. Will give this a go and let you know if I run into any issues.

**Comment by epantera** [comment]
Dear @alexphelps, do you have any feedback about this first use ?

**Comment by alexphelps** [comment]
The instructions really helped! We were up and running in no time. No real valuable change suggestions for now. :)
